# Generated by Django 4.1 on 2022-10-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='release_date',
            field=models.DateField(),
        ),
    ]
