# Generated by Django 4.1 on 2022-10-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_author_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
